import { afterEach, describe, expect, test } from "bun:test";
import * as fs from "node:fs/promises";
import { join } from "node:path";
import { initializeJobs, disableJobs, validateJobsActivation } from "../lib/jobs/lifecycle.js";
import { jobsPaths, dispatchJobs, scheduleJobs, jobsStatus } from "../lib/jobs.js";
const roots = [];
async function fixture() { const root = await fs.realpath(await fs.mkdtemp("./ai-tmp/jobs-life-")); roots.push(root); return root; }
afterEach(async () => { await Promise.all(roots.splice(0).map((root) => fs.rm(root, { recursive: true, force: true }))); });
async function tree(path) { const result = {}; for (const entry of await fs.readdir(path, { withFileTypes: true })) result[entry.name] = entry.isDirectory() ? await tree(join(path, entry.name)) : await fs.readFile(join(path, entry.name), "utf8"); return result; }
describe("folder-only Jobs lifecycle", () => {
  test("init, disable, restore preserve every durable byte", async () => { const root = await fixture(); await initializeJobs(root); const paths = jobsPaths(root); for (const key of ["tasks", "completed", "state", "runs", "errors"]) await fs.writeFile(join(paths[key], "keep"), key); const before = await tree(paths.root); await disableJobs(root); expect(await tree(paths.disabled)).toEqual(before); await initializeJobs(root); expect(await tree(paths.root)).toEqual(before); });
  test("both folders collide and roots/layout reject symlinks", async () => { const root = await fixture(), paths = jobsPaths(root); await initializeJobs(root); await fs.mkdir(paths.disabled); await expect(initializeJobs(root)).rejects.toMatchObject({ code: "JOBS_COLLISION" }); await expect(disableJobs(root)).rejects.toMatchObject({ code: "JOBS_COLLISION" }); const other = await fixture(); await fs.symlink(root, jobsPaths(other).root); await expect(initializeJobs(other)).rejects.toMatchObject({ code: "JOBS_LAYOUT" }); });
  test("missing, disabled and damaged folders refuse run and CRUD", async () => { const root = await fixture(); await expect(dispatchJobs(root)).rejects.toMatchObject({ code: "JOBS_INACTIVE" }); await initializeJobs(root); await disableJobs(root); await expect(scheduleJobs(root, { action: "list" })).rejects.toMatchObject({ code: "JOBS_DISABLED" }); expect((await jobsStatus(root)).eligibility.state).toBe("disabled"); await initializeJobs(root); await fs.rm(jobsPaths(root).tasks, { recursive: true }); await expect(validateJobsActivation(root)).rejects.toMatchObject({ code: "JOBS_LAYOUT" }); });
  test("moved initialized project remains operational without old-path bytes", async () => { const parent = await fixture(), source = join(parent, "source"), moved = join(parent, "moved"); await fs.mkdir(source); await initializeJobs(source); await scheduleJobs(source, { action: "create", filename: "portable.md", source: "portable" }); await fs.rename(source, moved); expect((await jobsStatus(moved)).eligibility.state).toBe("enabled"); expect((await scheduleJobs(moved, { action: "list" })).tasks.map((task) => task.id)).toEqual(["portable.md"]); expect((await dispatchJobs(moved, { executor: async () => ({ outcome: "completed" }) })).outcomes).toHaveLength(1); expect(JSON.stringify(await tree(moved))).not.toContain(source); });
});
