/** LLM-oriented documentation manifests generated with the static site. */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { slugOf } from "./api.js";
import { site, ROOT } from "../site.js";

const sourceRoot = join(ROOT, "..");
const sourceText = (name) => readFileSync(join(sourceRoot, name), "utf8").trim();
const url = (path) => `${site.origin}${path}`;

/** A concise machine-readable documentation directory, following llms.txt conventions. */
export function llmsTxt(data) {
  const modules = data.modules
    .filter((module) => module.name !== "index")
    .map((module) => `- [${module.name} API](${url(`/api/${slugOf(module.name)}/`)})`)
    .join("\n");
  return `# Omoya\n\n> ${site.description}\n\nOmoya is a zero-dependency Bun agent harness for terminal, headless JSONL, embedded-library, and browser-chat use. This file is generated by the website build from the current source tree.\n\n## Documentation\n\n- [Home and getting started](${url("/")})\n- [API overview](${url("/api/")})\n- [Architecture](${url("/api/architecture/")})\n- [Public contracts](${url("/api/contracts/")})\n- [Tool catalog](${url("/api/tools/")})\n- [Settings schema](${url("/api/settings/")})\n\n## API modules\n\n${modules}\n\n## Complete documentation\n\n- [Full documentation](${url("/llms-full.txt")})\n\n## Notes\n\n- Canonical documentation origin: ${site.origin}\n- Generated API pages reflect the current source and JSDoc contracts.\n- Use the published documentation rather than inferring behavior from examples.\n`;
}

/** A self-contained Markdown corpus for clients that prefer one fetch. */
export function llmsFullTxt() {
  return `# Omoya documentation\n\nCanonical URL: ${site.origin}\n\nThis file is generated by \`website/build.js\` from the checked-in documentation sources.\n\n---\n\n${sourceText("README.md")}\n\n---\n\n${sourceText("API.md")}\n`;
}

/** Crawl directives and sitemap reference for a static deployment. */
export function robotsTxt() {
  return `User-agent: *\nAllow: /\n\nSitemap: ${url("/sitemap.xml")}\n`;
}

/** XML sitemap for every canonical HTML page emitted by the same build. */
export function sitemapXml(pages) {
  const entries = pages.map(({ path }) => `  <url><loc>${url(path)}</loc></url>`).join("\n");
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${entries}\n</urlset>\n`;
}
